### ISSUE TITLE
Angular cli release 1.0.0 mocks implementation is not working

### ISSUE THREAD

**Issue by Wolfium** [jjherscheid/ts-mocks#1] opened 2017-04-26 16:33 UTC
When using setup and is for a simulated behavior I get

        TypeError: Cannot read property '1' of null
            at Mock.Array.concat.Mock.setup (webpack:///~/ts-mocks/lib/mocks/mock.js:24:82 <- src/test.ts:108341:85)
            at testing_2.fakeAsync (webpack:///src/app/core/auth/auth.guard.spec.ts:108:32 <- src/test.ts:11998:35)
            at Object.<anonymous> (webpack:///~/@angular/core/bundles/core-testing.umd.js:342:0 <- src/test.ts:6933:30)
            at ZoneDelegate.invoke (webpack:///~/zone.js/dist/zone.js:242:0 <- src/polyfills.ts:2890:26)
            at ProxyZoneSpec.Array.concat.ProxyZoneSpec.onInvoke (webpack:///~/zone.js/dist/proxy.js:79:0 <- src/test.ts:75506:39)
            at ZoneDelegate.invoke (webpack:///~/zone.js/dist/zone.js:241:0 <- src/polyfills.ts:2889:32)
            at Zone.run (webpack:///~/zone.js/dist/zone.js:113:0 <- src/polyfills.ts:2761:43)
            at Object.<anonymous> (webpack:///~/zone.js/dist/jasmine-patch.js:102:0 <- src/test.ts:75221:34)
            at ZoneQueueRunner.Array.concat.jasmine.QueueRunner.ZoneQueueRunner.execute (webpack:///~/zone.js/dist/jasmine-patch.js:132:0 <- src/test.ts:75251:42)

I really like it but this become unusable

**Comment by jjherscheid** [comment] 2017-04-26 17:35
Dear Wolfium, 
I am currently working on a angular click 1.0.0 project and have no issues. Can you please show some more information of your test. Or share an example? I will look into the problem.
Regards,
Johan

**Comment by Wolfium** [comment] 2017-04-27 20:19
Will try to isoleate an example repro code and will let you know...

**Comment by jjherscheid** [comment] 2017-04-28 15:19
Example repo would be great, but also some code snippet from the unit test could maybe help. Trying to reproduce the problem, but still no errors found with CLI 1.0.0. 
But I see fakeAsync  and Guard in the stacktrace so maybe it is something with that.

**Comment by jjherscheid** [comment] 2017-05-03 06:10
For now closing issue because cannot reproduce

**Closed by jjherscheid** 2017-05-03 06:10 UTC
